save_best: False
logger:
  classname: bbrl.utils.logger.TFLogger
  log_dir: outputs/TD3
  cache_size: 10000
  every_n_seconds: 10
  verbose: False
  
es_algorithm:
  device : cpu
  pop_size: 20
  elites_nb: 10
  sigma : 0.2
  noise_multiplier: 0.8
  noise_limit: 1e-5
  diag_cov : True
  active : True
  classname : ES.cov_matrix.CEM

algorithm:
  seed: 432
  max_grad_norm: 0.5
  epsilon: 0.02
  n_envs: 1
  n_steps: 100
  eval_interval: 2000
  nb_evals: 10
  gae: 0.8
  max_epochs: 21000
  discount_factor: 0.98
  buffer_size: 2e5
  batch_size: 64
  tau_target: 0.05
  learning_starts: 10000
  action_noise: 0.1
  policy_delay: 2
  architecture:
      actor_hidden_size: [400, 300]
      critic_hidden_size: [400, 300]
  learner:
    classname: models.models.ContinuousDeterministicActor
  num_processes: 12
      

gym_env:
  classname: __main__.make_gym_env
  #env_name: Pendulum-v1
  env_name: Swimmer-v2
  #env_name: CartPoleContinuous-v1
actor_optimizer:
  classname: torch.optim.Adam
  lr: 1e-3

critic_optimizer:
  classname: torch.optim.Adam
  lr: 1e-3
  
