params=
  save_best: False
  logger:
    classname: "bbrl.utils.logger.TFLogger"
    log_dir: "./tmp/" + str(time.time())
    cache_size: 10000
    every_n_seconds: 10
    verbose: False   

  algorithm:
    seed: 5
    epsilon": 0.02
    n_envs": 1
    n_steps": 100
    eval_interval: 2000
    nb_evals: 10
    gae: 0.8
    max_epochs: 3500
    discount_factor: 0.99
    architecture :{"hidden_size": [256, 256]
  
  gym_env :
    classname: __main__.make_env
    env_name: "CartPole-v1"
  
  optimizer:
  
    classname: "torch.optim.Adam"
    lr: 2e-3
